packages:
  - "packages/*"
  - "src"

catalogs:
  dev:
    "@solid-primitive/shared": ^0.1.0-beta.3
    "@solid-primitive/web": ^0.1.0-beta.1
    solid-js: ^1.9.5
    tsdown: ^0.22.0
    unplugin-solid: ^1.0.0
    typescript: ^6.0.0
    tinyglobby: ^0.2.15
    turbo: ^2.8.12
    vite: ^7.3.1
  types:
    "@types/node": "20.19.0"
  test:
    "@vitest/coverage-v8": ^4.1.0
    "@vitest/ui": ^4.1.0
    vitest: ^4.1.0
    jsdom: ^28.1.0
    vite-plugin-solid: ^2.11.0
  docs:
    "@mdx-js/mdx": ^2.3.0
    "@solidjs/router": ^0.15.0
    "@solidjs/start": 2.0.0-alpha.2
    "@mdx-js/rollup": ^3.0.0
    rehype-pretty-code: ^0.14.3
    shiki: ^4.0.2
